export const FETCH_FRIENDS_SUCCESS = 'friends/FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_ERROR = 'friends/FETCH_FRIENDS_ERROR';

export const FETCH_FRIENDSINCOMING_SUCCESS = 'friends/FETCH_FRIENDSINCOMING_SUCCESS';
export const FETCH_FRIENDSINCOMING_ERROR = 'friends/FETCH_FRIENDSINCOMING_ERROR';

export const FETCH_FRIENDSOUTGOING_SUCCESS = 'friends/FETCH_FRIENDSOUTGOING_SUCCESS';
export const FETCH_FRIENDSOUTGOING_ERROR = 'friends/FETCH_FRIENDSOUTGOING_ERROR';

export const SEND_FRIENDSHIP_SUCCESS = 'friends/SEND_FRIENDSHIP_SUCCESS';
export const SEND_FRIENDSHIP_ERROR = 'friends/SEND_FRIENDSHIP_ERROR';

export const ACCEPT_FRIENDSHIP_SUCCESS = 'friends/ACCEPT_FRIENDSHIP_SUCCESS';
export const CANCEL_FRIENDSHIP_SUCCESS = 'friends/CANCEL_FRIENDSHIP_SUCCESS';
export const REJECT_FRIENDSHIP_SUCCESS = 'friends/REJECT_FRIENDSHIP_SUCCESS';

export const ADD_NEW_FRIEND = 'friends/ADD_NEW_FRIEND';
export const NEW_INCOMING_REQUEST = 'friends/NEW_INCOMING_REQUEST';
