export const SEARCH_FRIENDS_SUCCESS = 'friends/SEARCH_FRIENDS_SUCCESS';
export const SEARCH_FRIENDS_ERROR = 'friends/SEARCH_FRIENDS_ERROR';

export const FETCH_FRIENDS_SUCCESS = 'friends/FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_ERROR = 'friends/FETCH_FRIENDS_ERROR';

export const FETCH_FRIENDSINCOMING_SUCCESS = 'friends/FETCH_FRIENDSINCOMING_SUCCESS';
export const FETCH_FRIENDSINCOMING_ERROR = 'friends/FETCH_FRIENDSINCOMING_ERROR';

export const FETCH_FRIENDSOUTGOING_SUCCESS = 'friends/FETCH_FRIENDSOUTGOING_SUCCESS';
export const FETCH_FRIENDSOUTGOING_ERROR = 'friends/FETCH_FRIENDSOUTGOING_ERROR';
